### ISSUE TITLE
show() method

### ISSUE THREAD

**Issue by alsaleem00** [tiran133/jQuery.ptTimeSelect#2]
I have several inputs that need to set time in.
I chose to make a js function that will open the pttimeselect with field name.
This is the example I used 

> $('input[name="eStart"]').ptTimeSelect({ zIndex: 100, hoursLabel: 'HRS'}).show(); 

but the problem is it does not show (popup) upon calling show(). Is show() supported?

**Comment by tiran133** [comment]
show is not a method. But the popup is trigger when the input is focused. 

So 

```js
$('input[name="eStart"]').ptTimeSelect({ zIndex: 100, hoursLabel: 'HRS'}).focus();
```

should work.

**Comment by alsaleem00** [comment]
yes. It works. Thanks.
